/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pajak;

/**
 *
 * @author LENOVO
 */
public class no2 extends javax.swing.JFrame {

    /**
     * Creates new form no2
     */
    public no2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pKanan = new javax.swing.JPanel();
        pKiri = new javax.swing.JPanel();
        pBawah = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        pTengah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPendapatan = new javax.swing.JTextField();
        tfAset = new javax.swing.JTextField();
        tfPajak = new javax.swing.JTextField();
        tfGajiAkhir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAtas.setBackground(new java.awt.Color(183, 224, 224));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("PENGHITUNG PAJAK GAJI");

        javax.swing.GroupLayout pAtasLayout = new javax.swing.GroupLayout(pAtas);
        pAtas.setLayout(pAtasLayout);
        pAtasLayout.setHorizontalGroup(
            pAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtasLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        pAtasLayout.setVerticalGroup(
            pAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(pAtas, java.awt.BorderLayout.PAGE_START);

        pKanan.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pKananLayout = new javax.swing.GroupLayout(pKanan);
        pKanan.setLayout(pKananLayout);
        pKananLayout.setHorizontalGroup(
            pKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        pKananLayout.setVerticalGroup(
            pKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(pKanan, java.awt.BorderLayout.LINE_END);

        pKiri.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pKiriLayout = new javax.swing.GroupLayout(pKiri);
        pKiri.setLayout(pKiriLayout);
        pKiriLayout.setHorizontalGroup(
            pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pKiriLayout.setVerticalGroup(
            pKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(pKiri, java.awt.BorderLayout.LINE_START);

        pBawah.setBackground(new java.awt.Color(229, 245, 245));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBawahLayout = new javax.swing.GroupLayout(pBawah);
        pBawah.setLayout(pBawahLayout);
        pBawahLayout.setHorizontalGroup(
            pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBawahLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pBawahLayout.setVerticalGroup(
            pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBawahLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(pBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(36, 36, 36))
        );

        getContentPane().add(pBawah, java.awt.BorderLayout.PAGE_END);

        pTengah.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("Pendapatan                  :");

        jLabel3.setText("Total Aset Kendaraan  :");

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jLabel4.setText("Pajak                              :");

        jLabel5.setText("Gaji Akhir                      :");

        tfPajak.setEditable(false);
        tfPajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPajakActionPerformed(evt);
            }
        });

        tfGajiAkhir.setEditable(false);

        javax.swing.GroupLayout pTengahLayout = new javax.swing.GroupLayout(pTengah);
        pTengah.setLayout(pTengahLayout);
        pTengahLayout.setHorizontalGroup(
            pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTengahLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pTengahLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfGajiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTengahLayout.createSequentialGroup()
                        .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAset, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(tfPendapatan)))
                    .addGroup(pTengahLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(tfPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHitung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pTengahLayout.setVerticalGroup(
            pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTengahLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(btnHitung)
                .addGap(25, 25, 25)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfGajiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        getContentPane().add(pTengah, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        double pendapatan = Double.parseDouble(tfPendapatan.getText());
        int asetKendaraan = Integer.parseInt(tfAset.getText());
    
        // Inisialisasi variabel pajak
        double pajakPersen = 0.0;
        
        if (pendapatan >= 10_000_000 && asetKendaraan >= 3) {
            pajakPersen = 15.0;
        } else if (pendapatan >= 5_000_000 && asetKendaraan == 2) {
            pajakPersen = 10.0;
        } else if (pendapatan >= 5_000_000 && asetKendaraan == 1) {
            pajakPersen = 7.0;
        } else if (pendapatan < 5_000_000 && asetKendaraan == 1) {
            pajakPersen = 5.0;
        } else if (pendapatan < 5_000_000 && asetKendaraan == 0) {
            pajakPersen = 2.5;
        }
        
        double pajak = (pajakPersen / 100) * pendapatan;
        tfPajak.setText(pajakPersen + " %");
        
        double gajiAkhir = pendapatan - pajak;
        tfGajiAkhir.setText(String.valueOf(gajiAkhir));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        tfPendapatan.setText("");
        tfAset.setText("");
        tfPajak.setText("");
        tfGajiAkhir.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tfPajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPajakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new no2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pAtas;
    private javax.swing.JPanel pBawah;
    private javax.swing.JPanel pKanan;
    private javax.swing.JPanel pKiri;
    private javax.swing.JPanel pTengah;
    private javax.swing.JTextField tfAset;
    private javax.swing.JTextField tfGajiAkhir;
    private javax.swing.JTextField tfPajak;
    private javax.swing.JTextField tfPendapatan;
    // End of variables declaration//GEN-END:variables
}
